apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: mobbinginx
  name: mobbinginx
  namespace: mobbing
spec:
  replicas: 3
  selector:
    matchLabels:
      app: mobbinginx
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: mobbinginx
    spec:
      containers:
      - image: nginx
        name: nginx
        resources: {}
